name: olajfolt_web
description: Olajfolt autókarbantartás napló - Flutter Web
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  firebase_app_check: ^0.3.0
  flutter_slidable: ^3.1.0
  url_launcher: ^6.2.0
  package_info_plus: ^8.0.0
  
  # PDF Generáláshoz
  pdf: ^3.10.0
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
